version: '3.9'
services:
  server:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      PORT: 5005
    ports:
      - '5000:5005'

  mongodb-users:
    image: mongo:latest
    command: mongod --port 27018
    ports:
      - 27018:27018

  mongodb-products:
    image: mongo:latest
    command: mongod --port 27019
    ports:
      - 27019:27019
